baseURL = 'https://mathanath.fr/'
languageCode = 'fr'
title = 'Mathanath'
theme = 'mathanath-theme'
sectionPagesMenu = 'main'
[markup.goldmark.renderer]
    unsafe= true
[params]
    banner = 'Plus de place disponible pour l’année scolaire 24/25 mais vous pouvez d’ores et déjà me contacter pour la rentrée de septembre 2025'
[caches]
  [caches.images]
    dir = ':cacheDir/images'